version: '3'

services:
  etesync:
    container_name: ${CONTAINER_NAME:-etesync}
    hostname: ${CONTAINER_NAME:-etesync}
    build: src
    expose:
      - 8000
    volumes:
      - ./data:/data
      - ./etestatic:/var/www/static:rw
    environment:
      - SERVER=${SERVER:-uwsgi}
      - SUPER_USER=${SUPER_USER:-admin}
      - SUPER_PASS=${SUPER_PASS:-admin}
      - TZ=${TZ:-CET}
    network_mode: "bridge"
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - ${PORT}:80
    volumes:
      - ./etestatic:/var/www/static:ro
      - ./src/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - TZ=${TZ:-CET}
    links:
      - ${CONTAINER_NAME:-etesync}
    network_mode: "bridge"
