version: '2.3'

services:
  etesync:
    container_name: etesync
    hostname: etesync
    #image: victorrds/etesync:latest
    build: .
    expose:
      - 8000
    volumes:
      - ./data:/data
      - ./etestatic:/var/www/static:rw
    environment:
      - SERVER=uwsgi
      - SUPER_USER=admin
      - SUPER_PASS=NI0LHghaDm9GB9dZRmUbmgG2VwtCMHvB7sBOjI1Q4e
    network_mode: "bridge"
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 8443:443
      - 8080:80
    volumes:
      - ./etestatic:/var/www/static:ro
      - ./nginx-example.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - etesync
    network_mode: "bridge"
